export const CATEGORIES = [
  {
    name: "Developer",
    subCategories: [
      "Blockchain architecture",
      "Distributed systems",
      "Wallets",
      "Tooling",
      "DevOps",
      "Frontend development",
      "Backend development",
      "Security",
      "Risk management",
      "Network operations",
      "Infrastructure",
    ],
  },
  {
    name: "Developer relations",
    subCategories: [
      "Technical expertise",
      "Community engagement",
      "Public speaking",
      "Content creation",
      "Advocacy",
      "Feedback management",
      "Collaboration",
      "Empathy",
      "Problem-solving",
      "Product knowledge",
    ],
  },
  {
    name: "Product",
    subCategories: [
      "Product ownership",
      "Product management",
      "Business analysis",
      "Product design",
      "User research",
    ],
  },
  { name: "Project management", subCategories: ["Project management"] },
  {
    name: "Business development",
    subCategories: [
      "Presentation and communication",
      "Fundraising",
      "Investor Relations",
      "Partnership building",
      "Process improvement",
      "Stakeholder management",
      "Market research",
      "Marketing and sales",
      "Strategic thinking",
      "Tokenomics",
    ],
  },
  {
    name: "Operations",
    subCategories: [
      "Legal and regulatory",
      "Compliance",
      "HR and People Management",
      "Supply Chain Management",
      "Risk management",
    ],
  },
  {
    name: "Finance",
    subCategories: [
      "Accounting",
      "Taxation",
      "Financial Analysis",
      "Treasury Management",
      "Risk Management",
      "Payment Processing",
    ],
  },
  {
    name: "Data Science",
    subCategories: [
      "Data Visualization",
      "Data analysis",
      "Statistical Analysis",
      "Natural Language Processing",
      "Machine Learning",
      "Big Data",
      "Data Cleaning and Preprocessing",
      "Data Modeling",
    ],
  },
  {
    name: "Creative",
    subCategories: [
      "Brand strategy",
      "Brand identity",
      "Campaign creative",
      "Graphic design",
      "Motion graphics",
      "Copywriting - technical",
      "Copywriting - marketing",
      "Photography",
      "Sound Design",
      "Videography",
      "Photo retouching",
      "Illustration",
    ],
  },
  {
    name: "Marketing",
    subCategories: [
      "PR and media relations",
      "Social media management",
      "Paid advertising",
      "Influencer marketing",
      "Search engine optimization (SEO)",
      "Email marketing",
      "Analytics and reporting",
      "Content strategy",
    ],
  },
  {
    name: "Community engagement",
    subCategories: [
      "Community management",
      "Evangelism",
      "Event organizing",
      "Education and training",
    ],
  },
  {
    name: "Meme maker",
    subCategories: [
      "Humor",
      "Creativity",
      "Timeliness",
      "Shareability",
      "Community engagement",
      "Brand awareness",
      "Memetic appeal",
      "Tone",
      "Visual design",
      "Memetic longevity",
    ],
  },
  {
    name: "Math",
    subCategories: [
      "Cryptography",
      "Game theory",
      "Distributed systems",
      "Computational complexity",
      "Algebraic geometry",
      "Probability theory",
      "Numerical analysis",
      "Topology",
      "Graph theory",
      "Number theory",
    ],
  },
  {
    name: "Journalist",
    subCategories: [
      "Editor",
      "Investigative journalism",
      "Breaking news",
      "Feature writing",
      "Opinion writing",
      "Market analysis",
      "Interviewing",
      "Podcasting",
      "Video reporting",
      "Social media reporting",
      "Community reporting",
    ],
  },
  {
    name: "Founder",
    subCategories: [
      "Visionary",
      "Risk-Taker",
      "Resourceful",
      "Strategist",
      "Leadership",
      "Adaptable",
      "Perseverant",
      "Customer-Oriented",
      "Financially Savvy",
      "Collaborative",
    ],
  },
  {
    name: "Researcher",
    subCategories: [
      "Academic Researcher",
      "Applied Researcher",
      "Consensus mechanisms",
      "Cryptoeconomics",
      "Cryptography",
      "Governance Researcher",
      "Interoperability",
      "Market Researcher",
      "Privacy Researcher",
      "Protocol",
      "Regulation",
      "Scalability",
      "Security",
      "Social",
    ],
  },
];
